### PR TITLE
Made the session log out icon a bit smaller [FIXED]

### PR DESCRIPTION
**Pull request by kckarnige**
Before:
image

After:
image

### CODE REVIEW

**Comment by kckarnige** [comment]
Also, if you're reading this, maybe consider adding a license to the repo, I recommend the MIT license

**Review by Martinz64 — CHANGES_REQUESTED** [review]
You shouldn't use aria labels, as they depend on the selected language
The modifications won't work for anyone who doesn't have English as their discord language

**Comment by kckarnige** [comment]
Oh yeah, I forgot other languages exist 💀

**Comment by kckarnige** [comment]
How's this?

**Review by Martinz64 — APPROVED** [review]
Looks good

**Pull request merged**
